### ISSUE TITLE
Repo ban

### ISSUE THREAD

**Issue by Selfie-bd** [GopalSaraf/TorrentLeechBot#5]
Your Repo banned 😐 @GopalSaraf `Close It`

`Make it Achieve 🗂️`

**Comment by GopalSaraf** [comment]
@Selfie-bd I don't think it is banned? where is the ban? plz explain

**Comment by GopalSaraf** [comment]
Not banned..

**Comment by Selfie-bd** [comment]
2 heruko account suspended
